'use client';
import {useState,useEffect} from 'react';
import {Plane,ArrowUpRight,Bookmark,SlidersHorizontal,MapPin,Search as SearchIcon,ArrowRight,Check,Clock,ExternalLink,X} from 'lucide-react';
import {regions,stopText,googleLink,validate,type Search,type Flight} from '../lib/flights';
const airports=[['RNO','Reno–Tahoe','Close to home'],['SMF','Sacramento','More possibilities'],['SFO','San Francisco','International gateway'],['OAK','Oakland','Across the bay']];
const initial:Search={origins:['RNO','SMF','SFO','OAK'],destinations:'LHR,CDG,LIS,MAD,BCN,FCO,AMS,KEF',depart:'2027-03-27',back:'2027-04-03',oneway:false,adults:3,children:0,cabin:'1',stops:1,duration:24,budget:0,sort:'price'};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const duration=(n:number)=>`${Math.floor(n/60)}h ${n%60}m`;
export default function Home(){
 const [s,setS]=useState<Search>(initial),[region,setRegion]=useState('Europe'),[tab,setTab]=useState('explore'),[saved,setSaved]=useState<{name:string;search:Search}[]>([]),[key,setKey]=useState(''),[settings,setSettings]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[flights,setFlights]=useState<Flight[]>([]),[active,setActive]=useState<Search|null>(null),[outbound,setOutbound]=useState<Flight|null>(null),[timestamp,setTimestamp]=useState(''),[hasSearched,setHasSearched]=useState(false);
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('flight-scout-saved')||'[]');setSaved(data.filter((x:any)=>{try{validate(x.search);return typeof x.name==='string'}catch{return false}}));}catch{}},[]);
 const update=(k:keyof Search,v:any)=>setS(p=>({...p,[k]:v}));
 function save(){try{validate(s);const next=[{name:`${s.origins.join(' / ')} → ${s.destinations} · ${s.depart}`,search:{...s}},...saved].slice(0,12);localStorage.setItem('flight-scout-saved',JSON.stringify(next));setSaved(next);setMessage('Search saved on this device.');}catch(e){setMessage((e as Error).message)}}
 async function search(config=s,selected?:Flight){try{validate(config)}catch(e){setMessage((e as Error).message);return}setLoading(true);setMessage('');setFlights([]);setActive({...config});setOutbound(selected||null);setHasSearched(true);setTab('explore');try{const res=await fetch('/api/flights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({search:config,key,token:selected?.token})});const data=await res.json() as {error?:string;flights:Flight[];searchedAt:string};if(!res.ok)throw Error(data.error||'Search failed.');setFlights(data.flights);setTimestamp(data.searchedAt);if(!data.flights.length)setMessage('No flights found. Try more stops, a longer duration, or fewer destination airports.');}catch(e){setMessage((e as Error).message)}finally{setLoading(false)}}
 const results=flights.filter(f=>(!s.budget||f.price!==null&&f.price<=s.budget)&&(s.stops===3||f.stops<=s.stops)&&f.duration<=s.duration*60).sort((a,b)=>s.sort==='price'?(a.price??Infinity)-(b.price??Infinity):a.duration-b.duration);
 const linkSearch=active||s;
 return <main>
 <header><a className="brand" href="/" aria-label="Flight Scout home"><span className="brandIcon"><Plane size={22}/></span>flight<span>scout</span><small>PERSONAL TRAVEL DESK</small></a><nav><button className={tab==='explore'?'nav active':'nav'} onClick={()=>setTab('explore')}>Explore</button><button className={tab==='saved'?'nav active':'nav'} onClick={()=>setTab('saved')}><Bookmark size={16}/>Saved <i>{saved.length}</i></button></nav><button className="settings" onClick={()=>setSettings(!settings)}><SlidersHorizontal size={17}/><span>Live search settings</span></button></header>
 <section className="hero"><div><div className="eyebrow"><span/> FOUR AIRPORTS. MORE POSSIBILITIES.</div><h1>A little flexible.<br/><em>A world of options.</em></h1><p>Start close to home. Find the flight worth going for.</p></div><div className="routeArt" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><span className="homePin">RNO</span><Plane className="artPlane" size={44}/><span className="destinationPin">ANYWHERE</span><div className="coordinates">39.50° N / 119.77° W</div></div></section>
 {settings&&<section className="settingsPanel"><div><h3>Connect live Google Flights results</h3><p>Enter your own <a href="https://serpapi.com/google-flights-api" target="_blank" rel="noreferrer">SerpApi key <ExternalLink size={12}/></a>. It stays in memory for this tab and is sent securely to the search server; it is never saved in your searches. Provider usage limits and charges may apply.</p></div><label>SerpApi API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste your API key"/></label><button onClick={()=>{setKey('');setMessage('API key cleared.')}}>Clear key</button></section>}
 {tab==='saved'?<section className="savedPanel"><div className="sectionTitle"><h2>Your saved searches</h2><span>Stored on this device</span></div>{!saved.length?<div className="empty"><Bookmark size={30}/><h3>Keep a good idea for later.</h3><p>Save a search to bring back its airports, dates, and filters.</p><button className="primary" onClick={()=>setTab('explore')}>Plan a trip</button></div>:saved.map((item,i)=><div className="savedRow" key={i}><div><strong>{item.search.origins.join(' / ')} → {item.search.destinations}</strong><p>{item.search.depart} {item.search.oneway?'· One way':`→ ${item.search.back}`} · {stopText(item.search.stops)}</p></div><button onClick={()=>{setS(item.search);setRegion('Custom');setTab('explore');setFlights([]);setActive(null);setHasSearched(false);}}>Load search <ArrowRight size={16}/></button><button aria-label="Delete saved search" onClick={()=>{const next=saved.filter((_,j)=>j!==i);setSaved(next);try{localStorage.setItem('flight-scout-saved',JSON.stringify(next))}catch{setMessage('Could not update saved searches.')}}}><X size={17}/></button></div>)}</section>:<>
 <section className="searchPanel"><div className="sectionTitle"><h2>Where are we headed?</h2><div className="segmented"><button className={!s.oneway?'selected':''} onClick={()=>update('oneway',false)}>Round trip</button><button className={s.oneway?'selected':''} onClick={()=>update('oneway',true)}>One way</button></div></div>
 <label className="fieldTitle">DEPARTURE AIRPORTS <span>Select any combination</span></label><div className="airports">{airports.map(([code,name,hint])=><button key={code} className={'airport '+(s.origins.includes(code)?'checked':'')} aria-pressed={s.origins.includes(code)} onClick={()=>update('origins',s.origins.includes(code)?s.origins.filter(x=>x!==code):[...s.origins,code])}><div><strong>{code}</strong><span className="checkbox">{s.origins.includes(code)&&<Check size={13}/>}</span></div><b>{name}</b><small>{hint}</small></button>)}</div>
 <div className="destinationRow"><div><label className="fieldTitle">DESTINATION</label><div className="presets">{['Europe','South America','Asia','Custom'].map(name=><button key={name} className={region===name?'selected':''} onClick={()=>{setRegion(name);if(regions[name])update('destinations',regions[name].map(x=>x.code).join(','));}}>{name}</button>)}</div><label className="destinationInput"><MapPin size={18}/><input aria-label="Destination airport codes" value={s.destinations} onChange={e=>{update('destinations',e.target.value.toUpperCase().replace(/\s/g,''));setRegion('Custom')}} placeholder="e.g. LIS,MAD,BCN"/></label><small className="hint">{region==='Custom'?'Enter up to 8 three-letter airport codes, separated by commas.':regions[region]?.map(x=>x.name).join(' · ')+' — editable shortlist, not every airport.'}</small></div><div className="dates"><label>DEPART<input aria-label="Departure date" type="date" value={s.depart} onChange={e=>update('depart',e.target.value)}/></label><label>RETURN<input aria-label="Return date" type="date" disabled={s.oneway} min={s.depart} value={s.back} onChange={e=>update('back',e.target.value)}/></label></div></div>
 <div className="detailsRow"><label>ADULTS (12+)<input type="number" min="1" max="9" value={s.adults} onChange={e=>update('adults',+e.target.value)}/></label><label>CHILDREN (2–11)<input type="number" min="0" max="8" value={s.children} onChange={e=>update('children',+e.target.value)}/></label><label>CABIN<select value={s.cabin} onChange={e=>update('cabin',e.target.value)}><option value="1">Economy</option><option value="2">Premium economy</option><option value="3">Business</option><option value="4">First</option></select></label><label className="stopsLabel"><span>MAXIMUM STOPS <b>{stopText(s.stops)}</b></span><input aria-label="Maximum stops" type="range" min="0" max="3" step="1" value={s.stops} onChange={e=>update('stops',+e.target.value)}/><div className="rangeLabels"><span>Nonstop</span><span>1</span><span>2</span><span>Any</span></div></label></div>
 <div className="searchBottom"><span><span className="dot"/> {s.origins.length} departure airports · USD · {s.adults+s.children} travelers</span><div><button onClick={save}><Bookmark size={16}/>Save</button><button className="primary" disabled={loading} onClick={()=>search()}><SearchIcon size={18}/>{loading?'Searching flights…':'Search live flights'}<ArrowRight size={18}/></button></div></div></section>
 <section className="resultsSection"><aside><h3><SlidersHorizontal size={17}/> Refine your options</h3><label>Max duration per direction <b>{s.duration} hours</b><input type="range" min="4" max="48" value={s.duration} onChange={e=>update('duration',+e.target.value)}/></label><label>Maximum displayed fare (USD)<input type="number" min="0" max="1000000" step="100" value={s.budget||''} placeholder="No limit" onChange={e=>update('budget',+e.target.value)}/></label><p>Filters narrow loaded results immediately. Search again after widening stops or duration, or changing your route and dates.</p><div className="tip"><span>THE BIGGER PICTURE</span><p>A cheaper Bay Area flight may mean a drive and a hotel. Compare the full travel day before booking.</p></div></aside>
 <div className="results"><div className="resultsHeader"><div><h2>{outbound?'Choose your return':hasSearched?'Flight options':'Your next trip starts here'}</h2><p>{flights.length?`${results.length} options · ${outbound?'Return':'Outbound'} duration includes layovers`: 'One search across your favorite departure airports.'}</p></div><label className="sortLabel">SORT BY<select value={s.sort} onChange={e=>update('sort',e.target.value)}><option value="price">Price: low to high</option><option value="duration">Duration: fastest first</option></select></label></div>
 {message&&<div role="status" className="notice">{message}</div>}
 {outbound&&<div className="notice">Selected outbound: {outbound.origin} → {outbound.destination}, {duration(outbound.duration)}. <button disabled={loading} onClick={()=>active&&search(active)}>Change outbound</button></div>}
 {flights.length>0&&<p className="fareNote">Provider-displayed fares in USD for the requested party; verify passenger breakdown and final total on Google Flights. {active?.oneway?'One-way search.':'Round-trip search; outbound offers are starting prices until a return is selected.'} Retrieved {new Date(timestamp).toLocaleString()}.</p>}
 {loading?<div className="empty"><span className="spinner"/><h3>Finding your way there…</h3><p>Searching your selected airports. This can take up to a minute.</p></div>:results.length?results.map(f=><article className="flight" key={f.id}><div className="flightTop"><span className="airline"><Plane size={16}/>{f.airline}</span><strong className="price">{f.price===null?'Fare unavailable':money(f.price)}</strong></div><div className="flightMain"><div><strong>{f.origin}</strong><small>{f.depart}</small></div><div className="flightPath"><span>{duration(f.duration)}</span><div/><small>{f.stops?`${f.stops} stop${f.stops>1?'s':''}`:'Nonstop'}</small></div><div><strong>{f.destination}</strong><small>{f.arrive}</small></div></div>{outbound&&<p className="fareNote">Both directions: {duration(outbound.duration+f.duration)} travel time, including layovers.</p>}<details><summary>Flight details & layovers</summary>{f.legs.map((l,i)=><p key={i}>{l.number} · {l.from} → {l.to}<br/>{l.depart} → {l.arrive} · {duration(l.duration)}</p>)}{f.layovers&&<p>Layovers: {f.layovers}</p>}<small>Airport-local dates and times.</small></details><div className="flightActions">{!active?.oneway&&!outbound&&f.token&&<button disabled={loading} onClick={()=>active&&search(active,f)}>Compare returns <ArrowRight size={14}/></button>}<a className="button" href={googleLink(linkSearch,outbound?.origin||f.origin,outbound?.destination||f.destination)} target="_blank" rel="noreferrer">Check on Google Flights <ArrowUpRight size={15}/></a></div></article>):<div className="empty"><div className="emptyIcon"><Plane size={29}/></div><h3>{flights.length?'No flights match these filters.':'Less searching. More exploring.'}</h3><p>{flights.length?'Raise your fare or duration limit to see more options.':'Connect a SerpApi key for live fares and sorting here, or start with a Google Flights search below.'}</p>{!flights.length&&<button onClick={()=>setSettings(true)}>Set up live search <ArrowRight size={15}/></button>}</div>}
 <div className="linkBox"><div><h3>Continue on Google Flights</h3><p>No API key needed. Search links use your current form; confirm dates, passengers, stops, and other filters after opening.</p></div><div className="googleLinks">{s.origins.map(origin=><a key={origin} href={googleLink(s,origin)} target="_blank" rel="noreferrer">{origin}<ArrowUpRight size={15}/></a>)}</div></div>
 </div></section></>}
 <footer><span><Plane size={14}/> FLIGHT SCOUT</span><p>Your airports. Your pace. Your next adventure.</p><small>Independent travel tool · Not affiliated with Google · Confirm fares before booking.</small></footer>
 </main>
}
