export const regions: Record<string, {code:string;name:string}[]> = {
 Europe:[{code:'LHR',name:'London'},{code:'CDG',name:'Paris'},{code:'LIS',name:'Lisbon'},{code:'MAD',name:'Madrid'},{code:'BCN',name:'Barcelona'},{code:'FCO',name:'Rome'},{code:'AMS',name:'Amsterdam'},{code:'KEF',name:'Iceland'}],
 'South America':[{code:'LIM',name:'Lima'},{code:'BOG',name:'Bogotá'},{code:'UIO',name:'Quito'},{code:'SCL',name:'Santiago'},{code:'EZE',name:'Buenos Aires'},{code:'GRU',name:'São Paulo'}],
 Asia:[{code:'HND',name:'Tokyo Haneda'},{code:'NRT',name:'Tokyo Narita'},{code:'ICN',name:'Seoul'},{code:'SIN',name:'Singapore'},{code:'BKK',name:'Bangkok'},{code:'DEL',name:'Delhi'},{code:'TPE',name:'Taipei'},{code:'HKG',name:'Hong Kong'}]
};
export type Search = {origins:string[];destinations:string;depart:string;back:string;oneway:boolean;adults:number;children:number;cabin:string;stops:number;duration:number;budget:number;sort:string};
export type Flight = {id:string;origin:string;destination:string;airline:string;price:number|null;duration:number;stops:number;depart:string;arrive:string;layovers:string;token?:string;legs:{number:string;from:string;to:string;depart:string;arrive:string;duration:number}[]};
export const stopText=(n:number)=>['Nonstop','Up to 1 stop','Up to 2 stops','Any stops'][n];
export function validate(s:Search){
 if(!s || !Array.isArray(s.origins)||!s.origins.length||s.origins.length>4||!s.origins.every(x=>['RNO','SMF','SFO','OAK'].includes(x))) throw Error('Select at least one departure airport.');
 if(typeof s.destinations!=='string'||!/^([A-Z]{3})(,[A-Z]{3}){0,7}$/.test(s.destinations)) throw Error('Enter 1–8 destination airport codes, separated by commas.');
 const date=(v:string)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
 if(!date(s.depart)||(!s.oneway&&(!date(s.back)||s.back<s.depart)))throw Error('Choose valid departure and return dates.');
 if(s.depart<new Date(Date.now()-86400000).toISOString().slice(0,10))throw Error('Choose a future departure date.');
 if(!Number.isInteger(s.adults)||s.adults<1||!Number.isInteger(s.children)||s.children<0||s.adults+s.children>9)throw Error('Choose 1–9 passengers, including at least one adult.');
 if(![0,1,2,3].includes(s.stops)||!['1','2','3','4'].includes(s.cabin)||!Number.isFinite(s.duration)||s.duration<1||s.duration>48||!Number.isFinite(s.budget)||s.budget<0||s.budget>1000000||!['price','duration'].includes(s.sort))throw Error('Check your search filters.');
}
export function params(s:Search){validate(s);return new URLSearchParams({engine:'google_flights',departure_id:s.origins.join(','),arrival_id:s.destinations,outbound_date:s.depart,...(!s.oneway?{return_date:s.back}:{}),type:s.oneway?'2':'1',adults:String(s.adults),children:String(s.children),travel_class:s.cabin,stops:String(s.stops===3?0:s.stops+1),sort_by:s.sort==='duration'?'5':'2',max_duration:String(s.duration*60),currency:'USD',hl:'en',gl:'us'});}
export function normalize(raw:any):Flight[]{return [...(raw.best_flights||[]),...(raw.other_flights||[])].filter(x=>Array.isArray(x.flights)&&x.flights.length).map((x:any,i:number)=>{const f=x.flights;return {id:String(i)+'-'+f.map((a:any)=>a.flight_number).join('-'),origin:f[0].departure_airport.id,destination:f.at(-1).arrival_airport.id,airline:[...new Set(f.map((a:any)=>a.airline))].join(' / '),price:typeof x.price==='number'?x.price:null,duration:x.total_duration,stops:f.length-1,depart:f[0].departure_airport.time,arrive:f.at(-1).arrival_airport.time,layovers:(x.layovers||[]).map((a:any)=>a.id+' · '+a.duration+' min'+(a.overnight?' overnight':'')).join(', '),token:x.departure_token,legs:f.map((a:any)=>({number:a.flight_number,from:a.departure_airport.id,to:a.arrival_airport.id,depart:a.departure_airport.time,arrive:a.arrival_airport.time,duration:a.duration}))};});}
export function googleLink(s:Search,origin?:string,dest?:string){const q=`${s.oneway?'one way':'round trip'} flights from ${origin||s.origins.join(', ')} to ${dest||s.destinations} on ${s.depart}${s.oneway?'':` returning ${s.back}`} for ${s.adults} adults${s.children?` and ${s.children} children`:''} ${['','economy','premium economy','business','first class'][Number(s.cabin)]} ${stopText(s.stops)}`;return 'https://www.google.com/travel/flights?q='+encodeURIComponent(q);}
